# Generated by Django 4.2.7 on 2023-11-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='height',
            name='height',
            field=models.IntegerField(),
        ),
    ]
