# Generated by Django 4.2.7 on 2023-11-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_preference_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='preferred_age',
            new_name='max_age',
        ),
        migrations.AddField(
            model_name='preference',
            name='min_age',
            field=models.IntegerField(null=True),
        ),
    ]
