# Generated by Django 4.2.7 on 2023-11-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_preference_preferred_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
