# Generated by Django 4.2.7 on 2023-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_gender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
