# Generated by Django 4.2.7 on 2023-11-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_community_name_religion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='name',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='name',
        ),
    ]
